[package]
name = "obsidian-sync"
version = "4.3.0
edition = "2021"
description = "Obsidian Git Sync — cross-platform vault synchronizer"
license = "MIT"
repository = "https://github.com/Kira361323/obsidian-sync-rust"

[dependencies]
clap = { version = "4", features = ["derive"] }
ureq = { version = "2", default-features = false, features = ["tls"] }
chrono = "0.4"
dirs = "5"
dialoguer = { version = "0.11", default-features = false }
comfy-table = "7"
self_update = { version = "0.41", default-features = false, optional = true, features = [
    "archive-tar",
    "archive-zip",
    "compression-flate2",
] }

[features]
default = []
self-update = ["dep:self_update"]

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
