[package]
name = "obsidian-sync"
version = "4.1.0"
edition = "2021"
description = "Obsidian Git Sync — cross-platform vault synchronizer"
repository = "https://github.com/Kira361323/obsidian-sync-rust"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
ureq = { version = "2", default-features = false, features = ["tls"] }
chrono = "0.4"
dirs = "5"
dialoguer = { version = "0.11", default-features = false }

[target.'cfg(not(target_os = "android"))'.dependencies]
self_update = { version = "0.41", default-features = false, features = [
    "archive-tar",
    "archive-zip",
    "compression-flate2",
] }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"